import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import RootLayoutContext from "@/components/RootLayout/RootLayoutContext";
import { Toaster } from "@/components/ui/toaster";
import SessionLayout from "@/components/RootLayout/SessionLayout";
import { ThemeProvider } from "@/components/theme-provider";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionLayout>
          <ThemeProvider attribute="class">
            <RootLayoutContext>
              {children}
              <Toaster />
            </RootLayoutContext>
          </ThemeProvider>
        </SessionLayout>
      </body>
    </html>
  );
}
